ichoose_web_application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include(('registration.urls','registration'), namespace='registration')),
    path('', include(('isell.urls','isell'), namespace='isell')),
    path('', include(('ilend.urls','ilend'), namespace='ilend')),
    path('', include(('delivery.urls','delivery'), namespace='delivery')),
    path('ichoose/', include(('ichoose.urls','ichoose'), namespace='ichoose')),
    
]
urlpatterns+= staticfiles_urlpatterns()
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ilend/urls.py
from django.urls import path

from . import views
app_name='loan_interface'


urlpatterns = [
    path('ilend/home/',views.display_home,name='home'),
    path('ilend/', views.HomePageView.as_view(), name='wallet'),
    path('ilend/charge/', views.charge, name='charge'),
    path('ilend/card/', views.addcard, name='card'),
    path('ilend/display_card/', views.displaycard, name='displaycard'),
    path('ilend/view_card/', views.viewcard, name='viewcard'),

]

isell/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('isell/home/', isell_home, name='isell_home'),
    path('isell/verification_request/', verification_request, name='verification_request'),
    path('isell/add_products/', add_products, name='add_products'),
    path('isell/add_new_product/', add_new_product, name='add_new_product'),
    path('isell/edit_product/', edit_product, name='edit_product'),
    path('isell/remove_product/', remove_product, name='remove_product'),


    path('isell/loan_details/', loan_details, name='loan_details'),
    path('isell/write_reply/', write_reply, name='write_reply'),
    path('isell/reply_customization_requests/', reply_customization_requests,
         name='reply_customization_requests'),
    path('isell/accept_reject_customization_requests/', accept_reject_customization_requests, name='accept_reject_customization_requests'),
    path('isell/customization_requests/', customization_requests, name='customization_requests'),
    path('isell/show_product/', show_product, name='show_product'),
    path('isell/delivered_products/', delivered_products, name='delivered_products'),
    path('isell/applied_loans/', applied_loans, name='applied_loans'),
    path('isell/show_order/', show_order, name='show_order'),
    path('isell/apply_loan/', apply_loan, name='apply_loan'),

    path('isell/export_data/', export_data, name='export_data'),
    path('isell/statistics/', statistics, name='statistics'),
]

isell/models.py
from djongo import models
from registration.models import User
from django import forms
from ichoose.list_field import CustomListField
from ichoose.models import seller_verification_process, sellers, sellers_form, product, product_form, ratings_comments, ratings_comments_form, customization, customization_form, order, order_form, loan, loan_form
from django.dispatch import receiver
from django.db.models.signals import post_save,pre_delete
from ilend.models import lenders,offlinewallet
from ichoose.models import product_abs, buyers

@receiver(post_save, sender=User)
def create_or_update_user(sender, instance, created, **kwargs):
    if created:
        new_buyer=buyers(buyer=instance)
        new_buyer.save()
        new_lender = lenders(lender=instance)
        new_lender.save()
        new_wallet = offlinewallet(user=instance, price=0)
        new_wallet.save()


@receiver(post_save, sender=product)
def create_or_update_product(sender, instance, created, **kwargs):
    if created:
        new_product_abs=product_abs(product_id=instance.id)
        new_product_abs.seller_id=instance.seller.id

        new_product_abs.date_of_post = instance.date_of_post

        new_product_abs.product_title = instance.product_title
        new_product_abs.category_1 = instance.category_1
        new_product_abs.category_2 = instance.category_2
        new_product_abs.product_description = instance.product_description

        new_product_abs.images = instance.images

        new_product_abs.product_name = instance.product_name
        new_product_abs.product_detail = instance.product_detail
        new_product_abs.product_color = instance.product_color
        new_product_abs.product_size = instance.product_size
        new_product_abs.product_price = instance.product_price
        new_product_abs.product_discount = instance.product_discount
        new_product_abs.product_final_price = instance.product_final_price

        new_product_abs.product_remaining_details = instance.product_remaining_details

        new_product_abs.additional_information = instance.additional_information
        new_product_abs.product_customisation_available = instance.product_customisation_available
        new_product_abs.additional_customization_information = instance.additional_customization_information

        new_product_abs.order_list = instance.order_list
        new_product_abs.ratings_comments = instance.ratings_comments
        new_product_abs.customization_requests_list = instance.customization_requests_list

        instance.seller.product_list.append(new_product_abs)
        instance.seller.save()

    else:

        products_seller = instance.seller
        products_seller_list=products_seller.product_list

        for i in range(len(products_seller_list)):
            if products_seller_list[i].product_id==instance.id:

                new_product_abs = product_abs(product_id=instance.id)
                new_product_abs.seller_id = instance.seller.id

                new_product_abs.date_of_post = instance.date_of_post

                new_product_abs.product_title = instance.product_title
                new_product_abs.category_1 = instance.category_1
                new_product_abs.category_2 = instance.category_2
                new_product_abs.product_description = instance.product_description

                new_product_abs.images = instance.images

                new_product_abs.product_name = instance.product_name
                new_product_abs.product_detail = instance.product_detail
                new_product_abs.product_color = instance.product_color
                new_product_abs.product_size = instance.product_size
                new_product_abs.product_price = instance.product_price
                new_product_abs.product_discount = instance.product_discount
                new_product_abs.product_final_price = instance.product_final_price

                new_product_abs.product_remaining_details = instance.product_remaining_details

                new_product_abs.additional_information = instance.additional_information
                new_product_abs.product_customisation_available = instance.product_customisation_available
                new_product_abs.additional_customization_information = instance.additional_customization_information

                new_product_abs.order_list = instance.order_list
                new_product_abs.ratings_comments = instance.ratings_comments
                new_product_abs.customization_requests_list = instance.customization_requests_list

                products_seller_list[i]=new_product_abs
                break
        products_seller.save()

@receiver(pre_delete, sender=product)
def delete_product(sender, instance,  **kwargs):

    products_seller = instance.seller
    products_seller_list=products_seller.product_list

    for i in range(len(products_seller_list)):
        if products_seller_list[i].product_id==instance.id:

            del(products_seller_list[i])

            break
    products_seller.save()

isell/views.py
from django.shortcuts import render,redirect, HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required,user_passes_test
from isell.models import seller_verification_process,sellers,product
from ichoose.models import buyers,customization,order,ratings_comments,loan
from django.core.files.storage import FileSystemStorage
from django.urls import reverse
import datetime,json
from django.contrib import messages
import csv
from .graphs import get_chart
from django.db.models import Count
from ichoose.category_types import categories

from ilend.models import offlinewallet, lenders


def test_verification(user):
    if user.verification_status==True:
        return True
    else:
        return False

def test_verification_application(user):
    if user.verification_applied==False:
        return True
    else:
        return False


@login_required(login_url='/login/')
def export_data(request):

    if request.method == "POST":
        user = request.user
        
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="ichoose_data.csv"'

        writer = csv.writer(response, delimiter=',')

        if request.POST.get('export_data_type') == "add_products":

            if request.POST.get('export_data_time_selected') and request.POST.get('export_data_time_selected')!="" and request.POST.get('export_data_time_selected')!="100":
                items = product.objects.filter(seller=sellers.objects.get(seller=user), date_of_post__gte=datetime.datetime.now()-datetime.timedelta(days=int(request.POST.get('export_data_time_selected')))).order_by('-date_of_post') if len(product.objects.filter(seller=sellers.objects.get(seller=user), date_of_post__gte=datetime.datetime.now()-datetime.timedelta(days=int(request.POST.get('export_data_time_selected'))))) > 0 else []
            else:
                items = product.objects.filter(seller=sellers.objects.get(seller=user)).order_by('-date_of_post') if len(product.objects.filter(seller=sellers.objects.get(seller=user))) > 0 else []


            writer.writerow(['Product_title', 'Product_category_1', 'Product_category_2', 'Product_final_price', 'Product_date_of_post', 'Product_number_of_orders'])

            for obj in items:
                writer.writerow([obj.product_title, obj.category_1, obj.category_2, obj.product_final_price, obj.date_of_post, len(obj.order_list) ])

        if request.POST.get('export_data_type') == "delivered_products":

            days_selected_time_filter =  request.POST.get('export_data_time_selected') 

            seller = sellers.objects.get(seller=request.user)
            items = []

            for each in seller.order_list:
                if each.delivery_status == True:
                    if days_selected_time_filter != "" and days_selected_time_filter != "100":
                        if (datetime.datetime.now() - each.date_of_order).days < int(days_selected_time_filter):
                            items.append(each)
                    else:     
                        items.append(each)

            writer.writerow(['Product_title', 'Product_category_1', 'Product_category_2', 'Product_final_price', 'Product_date_of_post', 'Product_number_of_orders'])

            for obj in items:
                writer.writerow([obj.product_title, obj.category_1, obj.category_2, obj.product_final_price, obj.date_of_post, len(obj.order_list) ])

        if request.POST.get('export_data_type') == "applied_loans":

            days_selected_time_filter =  request.POST.get('export_data_time_selected') 

            seller = sellers.objects.get(seller=request.user)
            items = []
            print("********************************************************")
            print(seller)
            for each in seller.loan_list:
                if days_selected_time_filter != "" and days_selected_time_filter != "100":
                    if (datetime.datetime.now() - each.loan_applied_date).days < int(days_selected_time_filter):
                        items.append(each)
                else:     
                    items.append(each)


            writer.writerow(['Order_id', 'loan amount', 'interest', 'loan status', 'loan applied date time', 'loan returned status', 'loan returned date time'])

            for obj in items:
                writer.writerow([obj.order_id, obj.loan_amount, obj.loan_intrest, obj.loan_status, obj.loan_applied_date, obj.loan_returned_status, obj.loan_returned_date ])

        if request.POST.get('export_data_type') == "pending_orders":

            days_selected_time_filter =  request.POST.get('export_data_time_selected') 

            seller=sellers.objects.filter(seller=request.user)
            items=[]
            try:
                for each in seller[0].order_list:
                    if each.delivery_status==False:
                        if days_selected_time_filter != "" and days_selected_time_filter != "100":
                            if (datetime.datetime.now() - each.date_of_order).days < int(days_selected_time_filter):
                                items.append(each)
                        else:     
                            items.append(each)
            except:
                pass


            writer.writerow(['Order product title', 'Order product name', 'price', 'quantity', 'total', 'order time', 'delivery deadline'])

            for obj in items:
                writer.writerow([obj.order_details.product_title, obj.order_details.product_name, obj.order_details.product_final_price, obj.quantity, obj.total_price, obj.date_of_order, obj.told_date_of_order ])


        return response

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/login/')
def isell_home(request):

    days_selected_time_filter = ""
    time_filter_dict = {'1':0, '3':1,'7':2,'30':3,'100':4}
    time_filter_list=["","","","","selected"]

    if request.method == 'POST':
        if request.POST.get('time') and (request.POST.get('time') in time_filter_dict.keys()):
            days_selected_time_filter = request.POST.get('time')
            time_filter_list=["","","","",""]   
            time_filter_list[time_filter_dict[request.POST.get('time')]] = "selected"

    seller=sellers.objects.filter(seller=request.user)
    pending_orders=[]
    try:
        for each in seller[0].order_list:
            if each.delivery_status==False:
                if days_selected_time_filter != "" and days_selected_time_filter != "100":
                    if (datetime.datetime.now() - each.date_of_order).days < int(days_selected_time_filter):
                        pending_orders.append(each)
                else:     
                    pending_orders.append(each)
    except:
        pass
    count = 0
    try:
        for each in seller[0].customization_requests_list:
            if each.accept_status == False and each.reject_status == False:
                count += 1
    except:
        pass

    walet_value = offlinewallet.objects.filter(user=lenders.objects.get(lender=request.user).lender)[0].price if offlinewallet.objects.filter(user=lenders.objects.get(lender=request.user).lender)[0].price else 0

    return render(request, 'index3.html',{'pending_orders':pending_orders,'count':count,'date':datetime.datetime.now(),'time_filter_list':time_filter_list, 'days_selected_time_filter':days_selected_time_filter, 'walet_value' : walet_value})

@login_required(login_url='/login/')
def statistics(request):
    
    product_chart_data = product.objects.filter(seller=sellers.objects.get(seller=request.user)).values('date_of_post').annotate(Count('id')).order_by('date_of_post')
    # print(product_chart_data[0])
    product_chart_data = product_chart_data[:100] if len(product_chart_data) > 100 else product_chart_data
    product_chart_data_month_year_filtered = {}
    for each in product_chart_data:
        if str(each['date_of_post'].day)+'_'+str(each['date_of_post'].month)+'_'+str(each['date_of_post'].year) in product_chart_data_month_year_filtered.keys():
            product_chart_data_month_year_filtered[str(each['date_of_post'].day)+'_'+str(each['date_of_post'].month)+'_'+str(each['date_of_post'].year)] += each['id__count']
        else:
            product_chart_data_month_year_filtered[str(each['date_of_post'].day)+'_'+str(each['date_of_post'].month)+'_'+str(each['date_of_post'].year)] = each['id__count']

    products_chart = get_chart(product_chart_data_month_year_filtered,'your_products')

    # print(products_chart.as_html())

    orders_chart_data=[]
    for each in sellers.objects.get(seller=request.user).product_list:
        orders_chart_data.extend(order.objects.filter(product=each.product_id).values('date_of_order').annotate(Count('id')).order_by('date_of_order'))

    print(orders_chart_data)
    orders_chart_data_month_year_filtered = {}
    for each in orders_chart_data : 
        if str(each['date_of_order'].day)+'_'+str(each['date_of_order'].month)+'_'+str(each['date_of_order'].year) in orders_chart_data_month_year_filtered.keys():
            orders_chart_data_month_year_filtered[str(each['date_of_order'].day)+'_'+str(each['date_of_order'].month)+'_'+str(each['date_of_order'].year)] += each['id__count']
        else:
            orders_chart_data_month_year_filtered[str(each['date_of_order'].day)+'_'+str(each['date_of_order'].month)+'_'+str(each['date_of_order'].year)] = each['id__count']

    orders_chart = get_chart(orders_chart_data_month_year_filtered,'your_orders')

    # print(orders_chart.as_html())

    orders_delivered_chart_data=[]
    for each in sellers.objects.get(seller=request.user).product_list:
        orders_delivered_chart_data.extend(order.objects.filter(product=each.product_id, delivery_status=True).values('date_of_order').annotate(Count('id')).order_by('date_of_order'))

    print(orders_delivered_chart_data)

isell/templates/verification_request.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>ISell</title>

    <!-- Fontfaces CSS-->
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
    <link href="{% static 'isell/css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'isell/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'isell/vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'isell/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'isell/vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static 'isell/vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'isell/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'isell/vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'isell/vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'isell/vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'isell/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'isell/vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'isell/css/theme.css' %}" rel="stylesheet" media="all">
    <style>



    </style>

</head>

<body class="animsition">
<div class="page-wrapper" style="padding-bottom:0px">
    <!-- HEADER DESKTOP-->



    <!-- PAGE CONTENT-->
    <div class="page-content--bgf7">
        <!-- BREADCRUMB-->

        <!-- END BREADCRUMB-->

        <!-- WELCOME-->
        <section class="welcome p-t-10" style="padding-bottom: 30px">
            <div class="container"style="margin-top: 4vh">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="title-4">Hey
                            <span>{{request.username}}!!</span>  &nbsp;We really appreciate your patience and enthusiasm to use our services!! <p style="text-align: center">We will do our best to improve your business once you are sucessfully verified.</p>
                        </h1>
                        <hr class="line-seprate">
                    </div>
                </div>
            </div>
        </section>












        <div class="col-lg-6" style="margin-left: 21% ">

            <div class="card" style="width: 1000px">
                <div class="card-header" style="font-size: x-large">
                    <strong>Verify your account</strong>
                </div>
                <div class="card-body card-block">
                    <form action="{% url 'isell:verification_request' %}" method="post" enctype="multipart/form-data" class="form-horizontal">
                    {% csrf_token %}
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label" style="font-weight: bold">Name</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" required  id="text-input" name="name" placeholder="Give your full name" class="form-control">

                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label" style="font-weight: bold">Phone number</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" required  id="text-input" name="ph_number" placeholder="This number will be sent OTP for verification" class="form-control">

                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label" style="font-weight: bold">Address line 1</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" required  id="text-input" name="address_line_1" placeholder="eg: 123 Main Street Room 22" class="form-control">

                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label" style="font-weight: bold">Address line 2</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" required  id="text-input" name="address_line_2" placeholder="eg: University Dorm" class="form-control">

                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label" style="font-weight: bold">city</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" required  id="text-input" name="city" placeholder="eg: hyderabad" class="form-control">

                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label" style="font-weight: bold">state</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" required  id="text-input" name="state" placeholder="eg: Telangana" class="form-control">

                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label" style="font-weight: bold">pincode</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <input type="text" required  id="text-input" name="pincode" placeholder="eg: 500001" class="form-control">

                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="textarea-input" class=" form-control-label" style="font-weight: bold">Purpose</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <textarea required id="textarea-input" name="purpose" rows="9" placeholder="This helps to make your verification process fast. Write your genuine purpose, financial status and why chose our platform." class="form-control"></textarea>
                            </div>
                        </div>

                        <div class="col-12 col-md-9"><br>
                            <label for="files" style="font-size: large;font-weight: bold">Give images of your <span style="color: #5cb85c">work</span> (preferably images with better resolution to make process fast).</label>
                                        <input type="file" style="font-size: large;font-weight: bold;float: right;border: lightgray 2px solid;padding: 4px;color: darkgray;" id="files" name="images" multiple><br>
                                        <br></div>

                        <br><br>

                        <div class="col-12 col-md-9"><br>
                            <label for="files" style="font-size: large;font-weight: bold">Add your <span style="color: #5cb85c">aadhar card 2 sided pdf</span> (and any other govt. verified documents to make process fast).</label>
                                        <input type="file" style="font-size: large;font-weight: bold;float: right;border: lightgray 2px solid;padding: 4px;color: darkgray;" id="files" name="files" multiple><br>
                                        <br></div>

                        <br><br><br>
                        <input  style="font-size: large;font-weight: bold;float: right;border: lightgray 2px solid;padding: 4px;color: darkgray;width:100%" type="submit">
                        <br><br><br>
                    </form><br>









                </div>
            </div>
        </div>
    </div>
    <!-- Jquery JS-->
    <script>
        function add_element_product() {
            var elmnt = document.getElementsByClassName("product_type")[0];
            var cln = elmnt.cloneNode(true);
            cln.val=""
            document.getElementById("add_product_type").appendChild(cln);
        }

        function add_type(x) {
            console.log("hello")
            var type_elmnt = document.getElementsByClassName("field_type")[0];
            var value_elmnt = document.getElementsByClassName("field_value")[0];
            var cln_typ = type_elmnt.cloneNode(true);
            var cln_val = value_elmnt.cloneNode(true);
            for (var i = 0; i < cln_typ.childNodes.length; i++) {
                cln_typ.childNodes[i].value = "";
            }
            for (var i = 0; i < cln_val.childNodes.length; i++) {
                cln_val.childNodes[i].value = "";
            }
            x.parentNode.appendChild(cln_typ);
            x.parentNode.appendChild(cln_val);
        }

        function add_custom_type(x) {
            console.log("hello")
            var type_elmnt = document.getElementsByClassName("custom_type")[0];
            var value_elmnt = document.getElementsByClassName("custom_value")[0];
            var cln_typ = type_elmnt.cloneNode(true);
            var cln_val = value_elmnt.cloneNode(true);
            for (var i = 0; i < cln_typ.childNodes.length; i++) {
                cln_typ.childNodes[i].value = "";
            }
            for (var i = 0; i < cln_val.childNodes.length; i++) {
                cln_val.childNodes[i].value = "";
            }
            x.parentNode.appendChild(cln_typ);
            x.parentNode.appendChild(cln_val);
        }

    </script>



    <script src="{% static 'isell/vendor/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'isell/vendor/bootstrap-4.1/popper.min.js' %}"></script>
    <script src="{% static 'isell/vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
    <!-- Vendor JS       -->
    <script src="{% static 'isell/vendor/slick/slick.min.js' %}">
    </script>
    <script src="{% static 'isell/vendor/wow/wow.min.js' %}"></script>
    <script src="{% static 'isell/vendor/animsition/animsition.min.js' %}"></script>
    <script src="{% static 'isell/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}">
    </script>
    <script src="{% static 'isell/vendor/counter-up/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'isell/vendor/counter-up/jquery.counterup.min.js' %}">
    </script>
    <script src="{% static 'isell/vendor/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'isell/vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'isell/vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'isell/vendor/select2/select2.min.js' %}">
    </script>

    <!-- Main JS-->
    <script src="{% static 'isell/js/main.js' %}"></script>

</body>

</html>
<!-- end document-->