ichoose/urls.py
from django.urls import path
from .views import *

app_name = 'ichoose'
urlpatterns = [
    path('', index, name='ichoose_home'),
    path('shop/', product_grid, name='ichoose_product_grid'),
    path('product/<int:id>/', single_product, name='ichoose_product'),
    path('wishlist/<int:id>/', wishlist, name='wishlist'),
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('show_wishlist/', show_wishlist, name='show_wishlist'),
    path('cart/', mycart, name='mycart'),
    path('remove/<int:id>/', remove, name='remove'),
    path('search/', search, name='search'),
    path('add_comments/<int:id>/', add_comment, name='add_comment'),
    path('shipping_details/', HomePageView.as_view(), name='shipping_details'),
    path('remove_wish/<int:id>/', remove_wish, name='remove_wish'),

    path('paayment/', charge, name='charge'),
    path('seller_api/', SellerVerifyAPI.as_view(), name='seller_verify'),
    path('verify_api/', SellVerifyAPI.as_view(), name='sell_verify'),
    path('flutter/', flutter_verify, name='flutter'),
    path('profile/', profile, name='profile'),

    path('customization_requests_buyer/', customization_requests_buyer, name='customization_requests_buyer')

]

ichoose_web_application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include(('registration.urls','registration'), namespace='registration')),
    path('', include(('isell.urls','isell'), namespace='isell')),
    path('', include(('ilend.urls','ilend'), namespace='ilend')),
    path('', include(('delivery.urls','delivery'), namespace='delivery')),
    path('ichoose/', include(('ichoose.urls','ichoose'), namespace='ichoose')),
    
]
urlpatterns+= staticfiles_urlpatterns()
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ilend/urls.py
from django.urls import path

from . import views
app_name='loan_interface'


urlpatterns = [
    path('ilend/home/',views.display_home,name='home'),
    path('ilend/', views.HomePageView.as_view(), name='wallet'),
    path('ilend/charge/', views.charge, name='charge'),
    path('ilend/card/', views.addcard, name='card'),
    path('ilend/display_card/', views.displaycard, name='displaycard'),
    path('ilend/view_card/', views.viewcard, name='viewcard'),

]

registration/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('', index, name='index'),
    path('home/', home, name='home'),
    path('login/', user_login, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', user_logout, name='logout'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         activate, name='activate'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path(r'^reset_password_url_verification/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         reset_password_url_verification, name='reset_password_url_verification'),
    path('reset_password/', reset_password, name='reset_password'),
    path('api/', OrderAPIView.as_view(), name='user_api'),

]

ilend/models.py
from djongo import models
from django import forms
from registration.models import User

class lenders(models.Model):
    lender = models.OneToOneField(User, on_delete=models.CASCADE, related_name='lender_user_id')


class lenders_form(forms.ModelForm):
    class Meta:
        model = lenders
        fields = (
            'lender',
        )


class offlinewallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_id_offlinewallet')

    price = models.IntegerField()
    # remain_priceforloans=models.IntegerField(default=0)


class lcards(models.Model):
    lender = models.OneToOneField(lenders, on_delete=models.CASCADE, related_name='lender_user_id_lcards')
    no_of_cards = models.ListField(default=[])
    money = models.ListField(default=[])
    
class lender_details(models.Model):
    lender = models.IntegerField(default=0)
    loan_amount=models.IntegerField(default=0)
    loan_on_order_id=models.IntegerField(default=0)
    

ilend/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.conf import settings 
from ilend.models import lender_details,lenders,offlinewallet,lcards
from ichoose.models import sellers,order
from django.views.generic.base import TemplateView
from registration.models import User
from datetime import datetime
import copy

import stripe
# Create your views here.
# stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_key ='sk_test_51H85ctJGt48B5LYp9cViFLQ9g8LtffZM4oAKsbu6ImxJ68NMZpkzuOq8sj2VbL7HBB0dHvBmthZG6RQkspKnUE7R00Uv7mugNb'


def display_home(request):
    loan_money=0
    money=0
    k=offlinewallet.objects.all()
    if len(k)>0:
      print(lenders.objects.get(lender=request.user).lender)
      p=offlinewallet.objects.filter(user=lenders.objects.get(lender=request.user).lender)
      if len(p)>0:
        m1=lcards.objects.filter(lender=lenders.objects.get(lender=request.user))
        if(len(m1)>0):
                for i in range(len(m1[0].money)):
                    loan_money+=m1[0].money[i]*m1[0].no_of_cards[i]
                
            
                
                context={'price':int(p[0].price)-loan_money,'user':lenders.objects.get(lender=request.user).lender}

        else:
            context={'price':int(p[0].price),'user':lenders.objects.get(lender=request.user).lender}
      else:
            context={'price':0,'user':lenders.objects.get(lender=request.user).lender}
        
      return render(request,'loan_interface/loan_home.html',context=context)
    else:
        context={'price':0,'user':lenders.objects.get(lender=request.user).lender}
        
        
        return render(request,'loan_interface/loan_home.html',context=context)
#to show left over money
def displaycard(request):
    loan_money=0
    g=offlinewallet.objects.all()
    if(len(g)>0):
        p=offlinewallet.objects.get(user=lenders.objects.get(lender=request.user).lender)
        m=lcards.objects.filter(lender=lenders.objects.get(lender=request.user))
        if(len(m)>0):
                for i in range(len(m[0].money)):
                    loan_money+=m[0].money[i]*m[0].no_of_cards[i]
                if(int(p.price)-loan_money==0):
                    context={'price':int(p.price)-loan_money,'value':0,'user':lenders.objects.get(lender=request.user).lender}
                
                else:
                    context={'price':int(p.price)-loan_money,'user':lenders.objects.get(lender=request.user).lender}

        else:
            context={'price':int(p.price), 'user':lenders.objects.get(lender=request.user).lender}
        
        return render(request,'loan_interface/add_cards.html',context=context)
    else:
         context={'price':0,'value':0,'user':lenders.objects.get(lender=request.user).lender}
        
         return render(request,'loan_interface/add_cards.html',context=context)
# to show card
def viewcard(request):
    loan_money=0
    a=offlinewallet.objects.all()
    if len(a)>0:
        p=offlinewallet.objects.get(user=lenders.objects.get(lender=request.user).lender)
        m=lcards.objects.filter(lender=lenders.objects.get(lender=request.user))
        dict1={25:0,50:0,75:0,100:0,125:0,150:0,175:0,200:0}
        money_list=[]
        cards_list=[]
        if(len(m)>0):
                for i in range(len(m[0].money)):
                    money_list.append(int(m[0].money[i]))
                    cards_list.append(int(m[0].no_of_cards[i]))
                for  j in dict1.keys():
                 for i in range(len(money_list)):
                    if(j==money_list[i]):
                        dict1[j]+=cards_list[i]
                print(dict1)
                
                
                context={"context":dict1,'user':lenders.objects.get(lender=request.user).lender}

        else:
            context={"context":dict1,'user':lenders.objects.get(lender=request.user).lender}
        return render(request,'loan_interface/view_cards.html',context=context)
    else:
        dict1={25:0,50:0,75:0,100:0,125:0,150:0,175:0,200:0}
        context={"context":dict1,'user':lenders.objects.get(lender=request.user).lender}
        return render(request,'loan_interface/view_cards.html',context=context)

# to add card in database

def addcard(request):
   loan_money=0
   
   if request.method == 'POST': 

        cards = request.POST.get('cards')
        money=request.POST.get('money') 
        g=offlinewallet.objects.all()
        
        print(lcards.objects.all())
        if len(g)>0:
            p=offlinewallet.objects.get(user=lenders.objects.get(lender=request.user).lender)
            print(p.price)
            y=lcards.objects.filter(lender=lenders.objects.get(lender=request.user))
            if len(y)>0:
                for i in range(len(y[0].money)):
                    loan_money+=y[0].money[i]*y[0].no_of_cards[i]
                
                if(int(p.price)-(int(loan_money)+(int(cards)*int(money)))<0):
                   return render(request,'loan_interface/add_cards.html')
                else:
                 print("a")
                 print(money in y[0].money)
                 if money in y[0].money :
                    print("a")
                    print(y[0].money)
                    y[0].no_of_cards[y[0].money.index(money)]+=int(cards)
                    
                    a=offlinewallet.objects.get(user=User.objects.filter(is_superuser=True)[0])
                    print(a)
                    a.price+=(int(cards)*int(money))
                    a.save(update_fields=['price'])
                    # p.remain_priceforloans=(p.remain_priceforloans-(int(cards)*int(money)))
                    p.save()
                   
                    y[0].save(update_fields=['no_of_cards'])
                 else:
                    print("b")
                    y[0].money.append(int(money))
                    y[0].no_of_cards.append(int(cards))
                    
                    a=offlinewallet.objects.get(user=User.objects.filter(is_superuser=True)[0])
                    a.price+=(int(cards)*int(money))
                    a.save(update_fields=['price'])
                    # p.remain_priceforloans=(p.remain_priceforloans-(int(cards)*int(money)))
                    p.save()
                    y[0].save()
                          

            else:
                
                print(int(p.price)-(int(cards)*int(money)))
                if(int(p.price)-(int(cards)*int(money))<0):
                   print(int(p.price)-(int(money)))
                   return render(request,'loan_interface/add_cards.html')
                else:
                    
                    a=offlinewallet.objects.get(user=User.objects.filter(is_superuser=True)[0])
                    
                    a.price+=(int(cards)*int(money))
                    a.save(update_fields=['price'])
                    # p.remain_priceforloans=(p.remain_priceforloans-(int(cards)*int(money)))
                    p.save()

                    lcards.objects.create(lender=lenders.objects.get(lender=request.user),money=[int(money)],no_of_cards=[int(cards)])

                    
        
            return render(request,'loan_interface/loan_home.html')
        
       
        
            
       
        
   
   
#stripe charges editing over
class HomePageView(TemplateView):
    template_name = 'loan_interface/add_money.html'

    def get_context_data(self, **kwargs): # new
        context = super().get_context_data(**kwargs)
        context['key'] = 'pk_test_51H85ctJGt48B5LYpJLPUNMnBk8F9AQdGn4Jt2MBhIA2G104PM6ke8DmL7ghTYmMyUbJK6YBYhecT029wgk4ikcZe00zFOfCNl6'#settings.STRIPE_PUBLISHABLE_KEY
        
        
        return context
def charge(request): # new
       if request.method == 'POST':
        charge = stripe.Charge.create(
            amount=int(request.POST.get('price'))*100,
            currency='inr',
            description='A Django charge',
            source=request.POST['stripeToken']
        ),
        username = lenders.objects.get(lender=request.user).lender
        price=request.POST.get('price')
        p=offlinewallet.objects.filter(user=lenders.objects.get(lender=request.user).lender)
       
        if len(p)>0:
            p1=offlinewallet.objects.get(user=lenders.objects.get(lender=request.user).lender) 
            p1.price = p1.price+int(price)
            # p1.remain_priceforloans=p1.price
            p1.save()
        else:
            # p=offlinewallet(username=username,price=price,remain_priceforloans=price)
            p.save()
      
        context={'price':request.POST.get('price')}
        return render(request, 'loan_interface/charge.html',context=context)

        

def sub_lists(list1): 
  
    # store all the sublists  
    sublist = [[]] 
      
    # first loop  
    for i in range(len(list1) + 1): 
          
        # second loop  
        for j in range(i + 1, len(list1) + 1): 
              
            # slice the subarray  
            sub = list1[i:j] 
            sublist.append(sub)
              
      
    return sublist 
b=lcards.objects.all()
possible_money=[]
for i in range(len(b)):
        print(b[i].no_of_cards,b[i].money)
        for j in range(len(b[i].no_of_cards)):
            for k in range((b[i].no_of_cards[j])):
              possible_money.append(str(b[i].money[j]))
possible_money2=[]
for i in possible_money:
    possible_money2.append(int(i))
subsets=sub_lists(possible_money2)
sum_subsets=[]
for i in subsets:
    sum_subsets.append(sum(i))
# print(sum_subsets)
mylist = list(dict.fromkeys(sum_subsets))
print(mylist)

# def money_loan(mon,lost_cards,p):
#     print(p,sum(lost_cards))
#     if(p==sum(lost_cards)):
#         a1=offlinewallet.objects.get(username="admin")
#         a1.price=a1.price-sum(lost_cards)
#         a1.save(update_fields=['price'])
#         return -1
#     else:
#             m1=lcards.objects.all()
        
#             for i in range(len(m1)):
                   

ilend/templates/loan_interface/add_money.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
 
     <!-- Site Metas -->
     <title>Ichoose</title>   
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'ilend/images/favicon.ico'%}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{% static 'ilend/images/apple-touch-icon.png'%}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'ilend/css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'ilend/style.css' %}">
    <!-- ALL VERSION CSS -->
    <link rel="stylesheet" href="{% static 'ilend/css/versions.css'%}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'ilend/css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'ilend/css/custom.css' %}">
    <!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'ilend/images1/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ilend/fonts1/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ilend/vendor1/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'ilend/vendor1/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ilend/vendor1/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'ilend/css1/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'ilend/css1/main.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="seo_version">

    

    <!-- Start header -->
	<header class="top-navbar">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="">
					<img src="{% static 'images/logo-seo.png' %}" alt="" />
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-seo" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbars-seo">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item"><a class="nav-link" href="{% url 'registration:home' %}" ><b>Home</b></a></li>
                        <li class="nav-item active"><a class="nav-link" href="{%url 'loan_interface:wallet'%}"><b>add money</b></a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'loan_interface:displaycard'%}"><b>Add Cards</b></a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'loan_interface:viewcard'%}"><b>view card</b></a></li>

                        <li class="nav-item "><a class="nav-link" href="{%url 'loan_interface:home'%}">Dashboard</a></li>
                       <li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							  Hi..{{user}}
							</a>
							<div class="  dropdown-menu" aria-labelledby="navbarDropdown">
							  <a class="dropdown-item,nav-link" href="{% url 'ichoose:profile' %}">Edit Profile</a>
							  
							  <div class="dropdown-divider"></div>
							  <a class="dropdown-item,nav-link" href="{% url 'registration:logout' %}">Logout</a>
							</div>
						  </li>                        </ul>

				</div>
			</div>
		</nav>
	</header>
	<!-- End header -->
    <div class="limiter">
		<div style=" width: 100%;  
        min-height: 100vh;
        display: -webkit-box;
        display: -webkit-flex;
        display: -moz-box;
        display: -ms-flexbox;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        padding: 15px;
        background: #64adca;
        background: -webkit-linear-gradient(-135deg,darkorange, #e4e7e7);
        background: -o-linear-gradient(-135deg,darkorange, #dce1e2);
        background: -moz-linear-gradient(-135deg,darkorange, #f1f3f3);
        background: linear-gradient(-135deg,darkorange, #f9fbfc);">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'ilend/images1/img-01.png' %}" alt="IMG">
				</div>

                <form class="login100-form validate-form" action="{% url 'loan_interface:charge'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.path }}  
					<span class="login100-form-title">
                        <h1 style="color: darkorange;"> <b>Add Money To Your Wallet</b></h1> 
					</span>

					

					<div class="wrap-input100 validate-input" data-validate = "money is required">
						<input class="input100" type="number" name="price" placeholder="Money" required >
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                         data-key={{key}}
                         data-name="ONLINE WALLET"
                         data-description="add money to your wallet"
                        
                         data-allow-remember-me="false"
                         data-label="ADD TO WALLET">
                    </script>
					</div>

					
				</form>
			</div>
		</div>
	</div>
    
	
    

	
    <footer class="footer" style="background-color:black">
        <div class="container" >
            <div class="row">
                <div class="col-lg-4 col-md-6 col-xs-12">
                    <div class="widget clearfix">
                        <div class="widget-title">
                            <img src="{% static 'images/logo-light.png' %}" alt="">
                        </div>
                        <h3 style="color: aliceblue;"><b> I choose is an E-Commerce Website which provides platform to buyers ,sellers,lenders.Sellers can start their business with zero inverstment with the help of lenders</b></h3>
                        
                    </div><!-- end clearfix -->
                </div><!-- end col -->
				
				<div class="col-lg-2 col-md-6 col-xs-12">
                    <div class="widget clearfix">
                        <div class="widget-title">
                            <h3 style="color:white">Information</h3>
                        </div >
                        <ul class="footer-links" >
                            <li><a href="#" style="color:darkorange">Home</a></li>
                            <li><a href="#" style="color:darkorange">about</a></li>
                            <li><a href="#" style="color:darkorange">services</a></li>
							<li><a href="#" style="color:darkorange">contact</a></li>
							<li><a href="#" style="color:darkorange">Faq</a></li>
							
                        </ul><!-- end links -->
                    </div><!-- end clearfix -->
                </div><!-- end col -->

                <div class="col-lg-3 col-md-6 col-xs-12">
                    <div class="widget clearfix">
						<div class="widget-title">
							<h3 style="color:white"> Services</h3>
						</div>
						<p style="color:darkorange">Main services offered are offline wallet service, pooling service,customization service</p>
						<div class="news-box">
							
						</div>
						
                        <div class="widget-title">
                            <h3 style="color:white">Social</h3>
                        </div>
                        <ul class="footer-links social-md">
                            <li><a class="fb btn-a" title="Facebook" data-tippy-animation="scale" href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a class="gi btn-a" title="Github" data-tippy-animation="scale" href="#"><i class="fa fa-github"></i> </a></li>
                            <li><a class="tw btn-a" title="Twitter" data-tippy-animation="scale" href="#"><i class="fa fa-twitter"></i> </a></li>
                            <li><a class="dr btn-a" title="Dribbble" data-tippy-animation="scale" href="#"><i class="fa fa-dribbble"></i> </a></li>
                            <li><a class="pi btn-a" title="Pinterest" data-tippy-animation="scale" href="#"><i class="fa fa-pinterest"></i> </a></li>
                        </ul><!-- end links -->
                    </div><!-- end clearfix -->
                </div><!-- end col -->
				
				<div class="col-lg-3 col-md-6 col-xs-12">
                    <div class="widget clearfix">
                        <div class="widget-title">
                            <h3 style="color:white">Contact Details</h3>
                        </div>

                        <ul class="footer-links">
                            <li ><a href="mailto:#" style="color:darkorange">info@yoursite.com</a></li>
                            <li><a href="#" style="color:darkorange">www.yoursite.com</a></li>
                            <li style="color:darkorange"> PO Box 16122 Collins Street West Victoria 8007 Australia</li>
                            <li style="color:darkorange">+61 3 8376 6284</li>
                        </ul><!-- end links -->
                    </div><!-- end clearfix -->
                </div><!-- end col -->
				
            </div><!-- end row -->
        </div><!-- end container -->
    </footer><!-- end footer -->
	
    <a href="#" id="scroll-to-top" class="dmtop global-radius" style="background-color: darkorange;"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="{% static 'ilend/js/all.js' %}"></script>
    <!-- ALL PLUGINS -->
	<script src="{% static 'ilend/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'ilend/js/custom.js' %}"></script>
	
	<script src="{% static 'ilend/js/jquery.ba-cond.min.js' %}"></script>
	<script src="{% static 'ilend/js/jquery.slitslider.js' %}"></script>
	<script type="text/javascript">	
			$(function() {
			
				var Page = (function() {

					var $nav = $( '#nav-dots > span' ),
						slitslider = $( '#slider' ).slitslider( {
							onBeforeChange : function( slide, pos ) {

								$nav.removeClass( 'nav-dot-current' );
								$nav.eq( pos ).addClass( 'nav-dot-current' );

							}
						} ),

						init = function() {

							initEvents();
							
						},
						initEvents = function() {

							$nav.each( function( i ) {
							
								$( this ).on( 'click', function( event ) {
									
									var $dot = $( this );
									
									if( !slitslider.isActive() ) {

										$nav.removeClass( 'nav-dot-current' );
										$dot.addClass( 'nav-dot-current' );
									
									}
									
									slitslider.jump( i + 1 );
									return false;
								
								} );
								
							} );

						};

						return { init : init };

				})();

				Page.init();
			
			});
		</script>
		
		<script>
			tippy('.btn-a')
		</script>
    <script src="{% static 'vendor1/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
        <script src="{% static 'vendor1/bootstrap/js/popper.js' %}"></script>
        <script src="{% static 'vendor1/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
        <script src="{% static 'vendor1/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
        <script src="{% static 'vendor1/tilt/tilt.jquery.min.js' %}"></script>
        <script >
            $('.js-tilt').tilt({
                scale: 1.1
            })
        </script>
    <!--===============================================================================================-->
        <script src="{% static 'js1/main.js' %}"></script>

</body>
</html>

ilend/templates/loan_interface/charge.html
<h2>Thanks, you paid <strong>${{price}}</strong>!</h2>