ichoose/urls.py
from django.urls import path
from .views import *

app_name = 'ichoose'
urlpatterns = [
    path('', index, name='ichoose_home'),
    path('shop/', product_grid, name='ichoose_product_grid'),
    path('product/<int:id>/', single_product, name='ichoose_product'),
    path('wishlist/<int:id>/', wishlist, name='wishlist'),
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('show_wishlist/', show_wishlist, name='show_wishlist'),
    path('cart/', mycart, name='mycart'),
    path('remove/<int:id>/', remove, name='remove'),
    path('search/', search, name='search'),
    path('add_comments/<int:id>/', add_comment, name='add_comment'),
    path('shipping_details/', HomePageView.as_view(), name='shipping_details'),
    path('remove_wish/<int:id>/', remove_wish, name='remove_wish'),

    path('paayment/', charge, name='charge'),
    path('seller_api/', SellerVerifyAPI.as_view(), name='seller_verify'),
    path('verify_api/', SellVerifyAPI.as_view(), name='sell_verify'),
    path('flutter/', flutter_verify, name='flutter'),
    path('profile/', profile, name='profile'),

    path('customization_requests_buyer/', customization_requests_buyer, name='customization_requests_buyer')

]

ichoose_web_application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include(('registration.urls','registration'), namespace='registration')),
    path('', include(('isell.urls','isell'), namespace='isell')),
    path('', include(('ilend.urls','ilend'), namespace='ilend')),
    path('', include(('delivery.urls','delivery'), namespace='delivery')),
    path('ichoose/', include(('ichoose.urls','ichoose'), namespace='ichoose')),
    
]
urlpatterns+= staticfiles_urlpatterns()
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ilend/urls.py
from django.urls import path

from . import views
app_name='loan_interface'


urlpatterns = [
    path('ilend/home/',views.display_home,name='home'),
    path('ilend/', views.HomePageView.as_view(), name='wallet'),
    path('ilend/charge/', views.charge, name='charge'),
    path('ilend/card/', views.addcard, name='card'),
    path('ilend/display_card/', views.displaycard, name='displaycard'),
    path('ilend/view_card/', views.viewcard, name='viewcard'),

]

isell/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('isell/home/', isell_home, name='isell_home'),
    path('isell/verification_request/', verification_request, name='verification_request'),
    path('isell/add_products/', add_products, name='add_products'),
    path('isell/add_new_product/', add_new_product, name='add_new_product'),
    path('isell/edit_product/', edit_product, name='edit_product'),
    path('isell/remove_product/', remove_product, name='remove_product'),


    path('isell/loan_details/', loan_details, name='loan_details'),
    path('isell/write_reply/', write_reply, name='write_reply'),
    path('isell/reply_customization_requests/', reply_customization_requests,
         name='reply_customization_requests'),
    path('isell/accept_reject_customization_requests/', accept_reject_customization_requests, name='accept_reject_customization_requests'),
    path('isell/customization_requests/', customization_requests, name='customization_requests'),
    path('isell/show_product/', show_product, name='show_product'),
    path('isell/delivered_products/', delivered_products, name='delivered_products'),
    path('isell/applied_loans/', applied_loans, name='applied_loans'),
    path('isell/show_order/', show_order, name='show_order'),
    path('isell/apply_loan/', apply_loan, name='apply_loan'),

    path('isell/export_data/', export_data, name='export_data'),
    path('isell/statistics/', statistics, name='statistics'),
]

registration/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('', index, name='index'),
    path('home/', home, name='home'),
    path('login/', user_login, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', user_logout, name='logout'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         activate, name='activate'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path(r'^reset_password_url_verification/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         reset_password_url_verification, name='reset_password_url_verification'),
    path('reset_password/', reset_password, name='reset_password'),
    path('api/', OrderAPIView.as_view(), name='user_api'),

]

ichoose/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse, get_object_or_404, redirect, render, HttpResponseRedirect
from .models import *
from isell.models import *
from ilend.models import *
from datetime import datetime
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
import stripe
from django.conf import settings
from django.views.generic.base import TemplateView
from django.db.models import Q
from .category_types import categories
from rest_framework import generics,filters
from ichoose.serializers import SellerVerify,SellUserVerify
from ichoose.models import seller_verification_process
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
# Create your views here.
stripe.api_key ='sk_test_51H85ctJGt48B5LYp9cViFLQ9g8LtffZM4oAKsbu6ImxJ68NMZpkzuOq8sj2VbL7HBB0dHvBmthZG6RQkspKnUE7R00Uv7mugNb'
#home page



class SellerVerifyAPI(generics.ListCreateAPIView):
    filter_backends = (filters.SearchFilter,)
    queryset = seller_verification_process.objects.all()
    serializer_class = SellerVerify


class  SellVerifyAPI(generics.ListCreateAPIView):
    filter_backends = (filters.SearchFilter,)
    queryset = seller_verification_process.objects.all()
    serializer_class = SellUserVerify

@csrf_exempt
def flutter_verify(request):
    body_unicode = request.body.decode('utf-8')
    final_dictionary = eval(body_unicode)
    print(final_dictionary)
    p=seller_verification_process.objects.filter(seller=User.objects.get(pk=int(final_dictionary['name'])))[0]
    p.Verification_step_1 = final_dictionary['Verification_step_1']
    p.Verification_step_2 = final_dictionary['Verification_step_2']
    p.Verification_step_3 = final_dictionary['Verification_step_3']
    if p.Verification_step_1 == p.Verification_step_2 == p.Verification_step_3 == 'True':
        User.verification_status = 'True'
        sellers.objects.create(sellers=user)
    else:
        User.verification_status = 'False'
    p.save()
    return render(request, '')
    if p.Verification_step_1 == p.Verification_step_2 == p.Verification_step_3 == "True":
        k= User.objects.get(pk=int(final_dictionary['name']))
        print(k)
        k.verification_status = "True"
        k.save()
        sellers.objects.create(seller=User.objects.get(pk=int(final_dictionary['name'])))
    else:
        User.verification_status = 'False'
    p.save()
    return redirect(reverse('isell:isell_home'))
    return redirect(reverse())



@login_required(login_url='/login/')
def profile(request):
    profile = User.objects.all()
    context = {
        'profile': profile,
    }
    return render(request, 'profile.html',context)




def index(request):
    inital = {"items":[],"price":0.0,"count":0,"size":[],"color":[]}
    session = request.session.get("data_", inital)
    product_wish = product.objects.filter(id__in=session["items"])
    count_cart= session["count"]
    cart_price = session["price"]
    product_ = product.objects.all().order_by('date_of_post')[:10]
    context ={
        'product_wish':product_wish,'count_cart':count_cart,'categories' : categories,"product":product_
    }
    return render(request, 'index-v2.html',context)


#shop
def product_grid(request):
    
    products = None
    inital = {"items":[],"price":0.0,"count":0,"size":[],"color":[]}
    session = request.session.get("data_", inital)
    product_wish = product.objects.filter(id__in=session["items"])
    count_cart= session["count"]
    cart_price = session["price"]
    cate = request.GET.get('category_1')
    cate_2 = request.GET.get('category_2')
    if cate:
        products = product.objects.filter(Q(category_1__exact=cate) | Q(category_2__exact=cate_2))
    else:
        products = product.objects.all()
    context={
        'product': products,
        'product_wish':product_wish,'count_cart':count_cart,
        'cart_price':cart_price,
        'categories' : categories,
        "title": cate 
    } 
    return render(request, 'shop.html',context)

# deatil view
def single_product(request, id=None):
    # instance = product.objects.get(id=1)
    instance = get_object_or_404(product,id=id)

    
    buyer_usernames=[]
    for each in instance.ratings_comments:
        buyer_usernames.append(buyers.objects.get(pk=each.buyer_id).buyer.username)
    data = zip(instance.ratings_comments,buyer_usernames)

    inital = {"items":[],"price":0.0,"count":0,"size":[],"color":[]}
    session = request.session.get("data_", inital)
    product_wish = product.objects.filter(id__in=session["items"])
    count_cart= session["count"]
    cart_price = session["price"] 

    customisations_available = {}
    product_remaining_details = {}
    product_siz = []
    product_siz = instance.product_size
    product_size = product_siz.split(',')

    for each1,each2 in instance.product_remaining_details[0].items():
        product_remaining_details[each1] = each2.split(',')
        product_remaining_details[each1].append('None')

    for k,v in instance.product_customisation_available[0].items():
        customisations_available[k] = v.split(',')
        customisations_available[k].append('None')

    color = []
    size = []
    for each in buyers.objects.get(buyer=request.user).customization_requests_list:
        if each.product_id == instance.pk : 
            try:
                color.append(each.accepted_details[0]['color'])
            except:
                pass
            try:
                size.append(each.accepted_details[0]['size'])
            except:
                pass

    context={
        'product':instance,
        'data':data,
        'product_wish':product_wish,'count_cart':count_cart,
        'customisations_available' : customisations_available,
        'product_remaining_details':product_remaining_details,
        'product_size':product_size,
        'color':color,
        'size':size
    }
    return render(request,'single-product.html',context)

#search

def search(request):
    q = request.GET["search"]
    products = product.objects.filter(Q(product_title__icontains=q) | Q(product_name__icontains=q))
    inital = {"items":[],"price":0.0,"count":0,"size":[],"color":[]}
    session = request.session.get("data_", inital)
    product_wish = product.objects.filter(id__in=session["items"])
    count_cart= session["count"]
    cart_price = session["price"] 
    context = {"product": products,
            'product_wish':product_wish,'count_cart':count_cart,
        'cart_price':cart_price,
        "title": q + " - search",
        'categories' : categories,}  #for title of web page

    return render(request, "shop.html", context)
#wishlist
def wishlist(request,id=None):
    
    inital = {"items":[],"price":0.0,"count":0,"size":[],"color":[]}
    session1 = request.session.get("data_", inital)
    session2 = request.session.get("mywishlist",inital)
    cart_count = session1["count"]
    product_ = product.objects.get(id=id)
    if id in session1["items"]:
        messages.error(request, "Already in cart")
    else:
        session2["items"].append(id)
        request.session["mywishlist"] = session2
    products = product.objects.filter(id__in=session2["items"])

    context = {
        'product':products,
        'count_cart':cart_count,
    }
    return redirect('ichoose:ichoose_product_grid')

def show_wishlist(request):
    inital = {"items":[],"price":0.0,"count":0,"size":[],"color":[]}
    sess = request.session.get("mywishlist", inital)
    session = request.session.get("data_", inital)
    products = product.objects.filter(id__in=sess["items"])
    count_cart= session["count"]

    context = {"products": products,
                'count_cart': count_cart,
            }
    return render(request, "wishlist.html", context)

def add_to_cart(request, id=None):
    """
        data = {"items" : ["slug1", "slug2"],
                "price" : 12342,
                "count" : 5
                }
        request.session["data_"] = data
    """
    this_product = product.objects.get(pk=id)
    
    inital = {"items":[],"size":[],"color":[],"price":0.0,"count":0,}
    session = request.session.get("data_", inital)
    
    # session["price"] = 0.0
    # session["count"] = 0
    session2 = request.session.get("mywishlist", inital)
    product_ = product.objects.get(id=id)
    if id in session["items"]:
        messages.error(request, "Already added to cart")
    elif id in session2["items"]:
        session2["items"].remove(id)
        session["items"].append(id)
        session["price"] += float(product_.product_final_price)
        session["count"] += 1
        session["color"] = request.POST.get('color')
        session["size"] = request.POST.get('size')
        request.session["data_"] = session
    else:
        
        session["color"] = [request.POST.get('color')]
        session["size"] = [request.POST.get('size')]
        session["items"].append(id)
        session["price"] += float(product_.product_final_price)
        session["count"] += 1
        request.session["data_"] = session
        
    products = product.objects.filter(id__in=session["items"])
    count_cart= session["count"]
    
    # return HttpResponseRedirect(reverse('ichoose:ichoose_product_grid',kwargs={'product_wish':products,'count_cart':count_cart,}))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def mycart(request):
    inital = {"items":[],"price":0.0,"count":0,"size":[],"color":[]}
    sess = request.session.get("data_", inital)
    products = product.objects.filter(id__in=sess["items"])
    count_cart= sess["count"]
    context = {"products": products,
                "count_cart":count_cart,
            }
    return render(request, "shop-cart.html", context)

def remove_wish(request,id):
    inital = {"items":[],"price":0.0,"count":0,"size":[],"color":[]}

    session = request.session.get("mywishlist", inital)

ichoose/templates/profile.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Profile</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

	<!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<!-- CSS Files -->
    <link href={% static 'assets/css/bootstrap.min.css' %} rel="stylesheet" />
	<link href={% static 'assets/css/gsdk-bootstrap-wizard.css' %} rel="stylesheet" />

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />
</head>

<body >

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'isell:isell_home' %}">IChoose</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav" style="position: absolute; right: 100px; top: 15px">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      {% if user.is_authenticated %}
          <a href="{% url 'ichoose:profile' %}" class="nav-item nav-link" title=""> Account </a>
          <a href="{% url 'registration:logout' %}" class="nav-item nav-link" title=""> logout </a>
      {% else %}
          <a href="{% url 'registration:login' %}" class="nav-item nav-link" title=""> Login </a>
          <a href="{% url 'registration:signup' %}" class="nav-item nav-link" title="">Sign up</a>

      {% endif %}
    </div>
  </div>
</nav>

</div>

<div class="line" style="background-color: black;width: 100%;height: 1px;position: absolute;top: 60px"></div>

<div class="image-container set-full-height" style="background-image: {% static 'assets/img/wizard.jpg' %}" >
    <!--   Big container   -->
    <div class="container" style="position: absolute;top: 30px;left: 150px;height: 500px">
        <div class="row">
        <div class="col-sm-8 col-sm-offset-2">

            <!--      Wizard container        -->
            <div class="wizard-container">

                <div class="card wizard-card" data-color="orange" id="wizardProfile">
                    <form action="" method="">
                <!--        You can switch ' data-color="orange" '  with one of the next bright colors: "blue", "green", "orange", "red"          -->

                    	<div class="wizard-header">
                        	<h3>
                        	   <b>BUILD</b> YOUR PROFILE <br>
                        	   <small>This information will let us know more about you.</small>
                        	</h3>
                    	</div>

						<div class="wizard-navigation">
							<ul>
	                            <li><a href="#about" data-toggle="tab">About</a></li>
	                        </ul>

						</div>

                        <div class="tab-content">
                            <div class="tab-pane" id="about">
                              <div class="row">
                                  <h4 class="info-text" style="padding-left: 100px"> Let's start with the basic information (with validation)</h4>
                                  <div class="col-sm-4 col-sm-offset-1">
                                     <div class="picture-container">
                                          <div class="picture">
                                              <img src="{% static 'assets/img/default-avatar.png' %}" class="picture-src" id="wizardPicturePreview" title=""/>
                                              <input type="file" id="wizard-picture">
                                          </div>
                                          <h6>Choose Picture</h6>
                                      </div>
                                  </div>
                                  <div class="col-sm-6">
                                      <div class="form-group">
                                        <label>Name <small>(required)</small></label>
                                        <input name="{{ profile.username }}" type="text" class="form-control" placeholder="Name">
                                      </div>
                                      <div class="form-group">
                                        <label>Mobile Number <small>(required)</small></label>
                                        <input name="{{ profile.mobile }}" type="text" class="form-control" placeholder="Last Name">
                                      </div>
                                      <div class="form-group">
                                            <label>Address</label>
                                            <input type="text" class="form-control" name="{{ profile.address }}" placeholder="Address">
                                      </div>
                                  </div>
                                  <div class="col-sm-10 col-sm-offset-1">
                                      <div class="form-group" style="width: 250px">
                                            <label>Product Count</label>
                                            <input type="number" class="form-control" name="{{ len_product }}" placeholder="Product Count">
                                      </div>
                                      <div class="form-group" style="width: 250px;position: absolute;right: 20px;top: 0px">
                                            <label>Order Count</label>
                                            <input type="number" class="form-control" name="{{ len_order }}" placeholder="Order Count">
                                      </div>
                                  </div>
                                  <div class="col-sm-10 col-sm-offset-1">
                                      <div class="form-group">
                                          <label>Email <small>(required)</small></label>
                                          <input name="{{ profile.email }}" type="email" class="form-control" placeholder="anything@gmail.com">
                                      </div>
                                  </div>
                              </div>
                            </div>
                        </div>
                        <div class="wizard-footer height-wizard">
                            <div class="pull-right">
                                <input type='button' class='btn  btn-fill btn-warning btn-wd btn-sm' name='finish' value='Finish' />
                            </div>

                            <div class="pull-left" style="padding-top: -20px;">
                                <button style="height: 30px" class='btn  btn-fill btn-default btn-wd btn-sm' href="{% url 'loan_interface:wallet' %}" value='wallet'>Wallet</button>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                </div>
            </div> <!-- wizard container -->
        </div>
        </div><!-- end row -->
    </div> <!--  big container -->

</div>

</body>

	<!--   Core JS Files   -->
	<script src='{% static 'assets/js/jquery-2.2.4.min.js' %}' type="text/javascript"></script>
	<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/js/jquery.bootstrap.wizard.js' %}" type="text/javascript"></script>

	<!--  Plugin for the Wizard -->
	<script src="{% static 'assets/js/gsdk-bootstrap-wizard.js' %}"></script>

	<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
	<script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>


</html>